### ISSUE TITLE
Comunicando Arduino con Otra cosa

### ISSUE THREAD

**Issue by miguelis** [tutugordillo/SED#2]
https://www.arduino.cc/en/Tutorial/MasterReader

Tendremos que hacer algo similar a esto.

**Comment by huig-** [comment]
Podría utilizarse esto https://github.com/adafruit/Adafruit_GPS. Incluye un timer para sincronizarse y leer cada cierto tiempo y no perder datos

**Comment by huig-** [comment]
in setup you can put:

    OCR0A = 0xAF;
    TIMSK0 |= _BV(OCIE0A);

then you add this function:

SIGNAL(TIMER0_COMPA_vect) {
  char c = Serial1.read();
    if (c) UDR0 = c;
}

**Comment by huig-** [comment]
Pruebas:
- Conectar TX0 a RX1 en el receiver: si funciona el problema es el sender, no funciona el problema es el receiver
- Conectar TX0 del sender al RX1 del receiver
- Probar el codigo de ejemplo que viene en SoftwareSerial

**Comment by huig-** [comment]
Parece ser que el problema era la funcion sprintf utilizando como argumento "%f", arduino no soporta esta opcion
